CREATE TABLE Accounts (
	Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	Username varchar(254) NOT NULL,
	Password varchar(254) NOT NULL
);

CREATE TABLE Faculty (
	Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	FacultyName varchar(150) NOT NULL,
	CONSTRAINT Unic_FacultyName UNIQUE (FacultyName)
);

CREATE TABLE Teacher (
	Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
	TeacherName varchar(254) NOT NULL
)

CREATE TABLE Speciality (
	Id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	FacultyId integer, 
	SpecialityName varchar(254)
);
ALTER TABLE Speciality ADD CONSTRAINT FK_Speciality_Faculty FOREIGN KEY (FacultyId) 
REFERENCES Faculty (Id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE Discipline (
	Id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	SpecialityId integer, 
	DisciplineName varchar(254)
);

ALTER TABLE Discipline ADD CONSTRAINT FK_Discipline_Speciality FOREIGN KEY (SpecialityId) 
REFERENCES Speciality (Id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE Labs (
	Id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	DisciplineId integer, 
	LabName varchar(254)
);

ALTER TABLE Labs ADD CONSTRAINT FK_Labs_Discipline FOREIGN KEY (DisciplineId) 
REFERENCES Discipline (Id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE Groups (
	Id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	SpecialityId integer, 
	CommingYear integer,
	GroupNumber integer
);

ALTER TABLE Groups ADD CONSTRAINT FK_Groups_Speciality FOREIGN KEY (SpecialityId) 
REFERENCES Speciality (Id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE SubGroups (
	Id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	GroupId integer, 
	SubGroupNumber integer
);

ALTER TABLE SubGroups ADD CONSTRAINT FK_SubGroups_Groups FOREIGN KEY (GroupId) 
REFERENCES Groups (Id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE Students (
	Id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	SubGroupId integer, 
	StudentName varchar(254)
);

ALTER TABLE Students ADD CONSTRAINT FK_Students_SubGroups FOREIGN KEY (SubGroupId) 
REFERENCES SubGroups (Id) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE TeacherWork (
	Id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	SubGroupId integer,
	DisciplineId integer,
	TeacherId integer
);

ALTER TABLE TeacherWork ADD CONSTRAINT FK_TeacherWork_SubGroup FOREIGN KEY (SubGroupId) 
REFERENCES SubGroups (Id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TeacherWork ADD CONSTRAINT FK_TeacherWork_Discipline FOREIGN KEY (DisciplineId) 
REFERENCES Discipline (Id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE TeacherWork ADD CONSTRAINT FK_TeacherWork_Teacher FOREIGN KEY (TeacherId) 
REFERENCES Teacher (Id) ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE LabsProgress (
	Id integer  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	DisciplineId integer,
	TeacherId integer,
	LabId integer,
	StudentId integer,
	LabProgress varchar(254)
);

ALTER TABLE LabsProgress ADD CONSTRAINT FK_LabsProgress_Discipline FOREIGN KEY (DisciplineId) 
REFERENCES Discipline (Id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE LabsProgress ADD CONSTRAINT FK_LabsProgress_Teacher FOREIGN KEY (TeacherId) 
REFERENCES Teacher (Id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE LabsProgress ADD CONSTRAINT FK_LabsProgress_Lab FOREIGN KEY (LabId) 
REFERENCES Labs (Id) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE LabsProgress ADD CONSTRAINT FK_LabsProgress_Student FOREIGN KEY (StudentId) 
REFERENCES Students (Id) ON DELETE CASCADE ON UPDATE CASCADE;